name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Replace API keys in JavaScript file
        run: |
          sed -i "s#const client_id = \\"\\";#const client_id = \\"${{ secrets.CLIENT_ID_SPOTIFY }}\\";#" js/complete-lyrics.js
          sed -i "s#const client_secret = \\"\\";#const client_secret = \\"${{ secrets.SECRET_CLIENT_ID_SPOTIFY }}\\";#" js/complete-lyrics.js

      - name: Build and deploy to GitHub Pages
        run: |
          npm run build
          npm install -g gh-pages
          gh-pages -d build -b main
